### ISSUE TITLE
Recipe doesn't show in JEI

### ISSUE THREAD

**Issue by traveldesign** [PssbleTrngle/CreateJetpack#10]
### What happened?

Hi there, I love the mod so much. I've been wanting someone to do a mod just like yours for a long time! 

I am unable to see the recipe in JEI. I dunno why. I was wondering if you could either send me a screenshot of the recipe or post it on the mod page. 

### Mod Version

1.1.1

### Minecraft Version

1.18

### Forge Version

40.1.68

**Comment by PssbleTrngle** [comment]
This is the recipe:

![image](https://user-images.githubusercontent.com/12880806/184195566-49ed800b-fdd6-4c08-a9b6-cee24e5ccea8.png)

I've just tested it and it should definitely show up. The JEI Version you mentioned [here](https://github.com/PssbleTrngle/BigSip/issues/15) is an alpha built, so there's probably some breaking change there, I would recommend you to downgrade to the latest stable JEI version for 1.18.2
