### ISSUE TITLE
Elytra Boost Is Paltry

### ISSUE THREAD

**Issue by Modulatus** [PssbleTrngle/CreateJetpack#102]
### What happened?

When using the jetpack with the Elytra activated, it provides a meager boost. A far cry from fireworks as it claims to provide. It uses constant pressure from the tank but only provides an intermittent puffs forward, hardly enough to get up to speed and definitely not enough to head at a moderate angle upwards.

### Loader

forge

### Mod Version

3.3.0

### Minecraft Version

1.19

**Comment by steve-the-player** [comment]
I didn't even realize it was providing any boost at all. Thought I was going crazy

**Comment by Modulatus** [comment]
> I didn't even realize it was providing any boost at all. Thought I was going crazy

Yeah it's intermittent at best. Pulses like 3 times a second giving a small boost each time, hardly enough to get off the ground if you don't already have some altitude.

Make sure you have elytra boost enabled in the server-side config (even if you're in singleplayer.)

**Comment by PssbleTrngle** [comment]
I'll take making it configurable into consideration. This issue will be closed since #87 is also asking for this
