### ISSUE TITLE
Cannot place Jetpack in trinkets slot

### ISSUE THREAD

**Issue by 3ncanis** [PssbleTrngle/CreateJetpack#106]
### What happened?

In the latest changelog for Fabric 4.1.1 on 1.20.1, it lists "fixed broken trinket support" though I am unable to place the jetpack into what I assume would be the backpack slot/cape slot.

### Loader

fabric

### Mod Version

4.1.1

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
You still have to allow the jetpack to go in the trinket slot using a datapack as described in the README, the latest release just fixes, that it will also work if it's placed there

**Comment by 3ncanis** [comment]
Ah I see thank you! Here's a datapack that works with Trinkets if you want to link on your page, I am however not able to see the model rendered on my player in third person when it's in the back slot.
[Create_Jetpack_Trinkets.zip](https://github.com/PssbleTrngle/CreateJetpack/files/14620392/Create_Jetpack_Trinkets.zip)

Here's when it's on my chest slot:
![Base Profile Screenshot 2024 03 15 - 15 18 39 61](https://github.com/PssbleTrngle/CreateJetpack/assets/133993378/624505bb-0257-420a-a74d-9f4b4467ccba)

And here's when it's in my backpack Trinkets slot:
![Base Profile Screenshot 2024 03 15 - 15 18 42 11](https://github.com/PssbleTrngle/CreateJetpack/assets/133993378/b0c0fe76-30f4-4401-8dc9-ba151093ceb1)

**Comment by masonjmj** [comment]
@PssbleTrngle I'm seeing the same issue on 1.20.1 with version 4.2.0 of the fabric version of the mod. Enabling the data pack allows it to be equipped and function correctly in the back trinket slot, but it doesn't render on the player.

**Comment by ImTrep** [comment]
i think the problem is related to this https://github.com/emilyploszaj/trinkets/wiki/%5BOLD%5D-Rendering-Trinkets

**Comment by PssbleTrngle** [comment]
Rendering the Jetpack (as well as the backtank) would require an extra render and will never work out of the box, until I specifically implement it, which I have for now decided not to do
