### ISSUE TITLE
Source code for fabric not linked in repo README

### ISSUE THREAD

**Issue by solonovamax** [PssbleTrngle/CreateJetpack#108]
### What happened?

The source for the [fabric version](https://github.com/PssbleTrngle/CreateJetpack-Fabric) is not linked in the repo README. Ideally they'd both be in the same repo, but if you want to keep the split repos & keep uploading both forge and fabric to the same modrinth/curseforge page, I'd appreciate if you noted somewhere in the README where to find the source for the fabric version.

### Loader

fabric

### Mod Version

N/A

### Minecraft Version

1.20

### Relevant log output

```Shell
N/A
```

**Comment by PssbleTrngle** [comment]
seems like I forgot that for this repo, thanks for the notice
