### ISSUE TITLE
I can't launch the game with this mod :(

### ISSUE THREAD

**Issue by Stasik22869777** [PssbleTrngle/CreateJetpack#119]
### What happened?

I play on FORGE 1.18.2 and when I install this mod I don’t understand why it doesn’t get stuck on me( .if you can help me I’ll be very helpful
![Снимок экрана 2024-07-25 222448](https://github.com/user-attachments/assets/226bbaf6-b8dc-4daa-be2e-9df8688624a9)

### Loader

forge

### Mod Version

1.6.1

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
Do you have Kotlin for Forge installed?

**Comment by Stasik22869777** [comment]
> Установлен ли у вас Kotlin для Forge?

no, thanks for helping, everything works now
