### ISSUE TITLE
Jetpack doesn't remain unbreakable after being placed in world

### ISSUE THREAD

**Issue by moonarts** [PssbleTrngle/CreateJetpack#121]
### What happened?

When you add the Unbreakable property to a jetpack (copper or netherite) either by command or by another mod like "Create: Unbreakable", the Unbreakable property doesn't remain after you place the jetpack in the world.

https://github.com/user-attachments/assets/e6d58201-f661-4325-bfce-04ab6a4cf02e

### Loader

fabric

### Mod Version

4.2.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
This should also not work with the backtank right?

**Comment by moonarts** [comment]
Just tested it out, you're right, placing an Unbreakable copper or netherite backtank in the world "delete" the Unbreakable tag.

But the enchantments stay, isn't it possible to keep the Unbreakable tag too ?

**Comment by PssbleTrngle** [comment]
It would be possible but it would only solve it for the jetpack, not for the backtank. That would be something I feel this "Create: Unbreakable" should do themself. Out of curiosity, what would the unbreakable tag do to the jetpack, since it does not have durability in a common sense?

**Comment by moonarts** [comment]
What do you mean by "it does not have durability" ?

I tested both copper and netherite jetpacks in an instance with only the "Create Jetpack" mod installed (and dependencies), as you can see, it breaks after being hit multiple times.

So I guess there is some sort of durability.

To answer your question, the Unbreakable tag (either added by command or another mod like "Create : Unbreakable Tools" would make the jetpack ... unbreakable ?

https://github.com/user-attachments/assets/e96a8d5e-c0b7-4f0c-9619-c901e2799888

**Comment by PssbleTrngle** [comment]
I am very sure neither the copper back nor the jetpack from this mod should have durablity/receive damage, since they work of the air system and do not even display a damage bar, even on your screen. Can you test if this also happens to you with the backtank too?

**Comment by moonarts** [comment]
Just tested both copper and netherite backtank from Create, they don't break or ran out of durability, only jetpacks do.

You can easily test this yourself if you want to.

**Comment by moonarts** [comment]
Did you manage to recreate this bug ?

Will it be fixed soon ?

**Comment by PssbleTrngle** [comment]
I will take a look at it once I find time, hopefully soon

**Comment by PssbleTrngle** [comment]
I was not able to reproduce the fact that jetpacks have durability, maybe this only happens when "Create: Unbreakable" is present. On the other hand, create 0.5.1.h just released which looks like it fixed the problem with placed backtank blocks (and by extension also jetpacks) not saving data from other mods

**Comment by moonarts** [comment]
As explained on August 15, 2024, I tested an instance with only the mod "Create Jetpack" installed (and dependencies), and it breaks after being hit multiple times (as shown in the video).

Did you test version 4.2.0 for Fabric 1.20.1 ?

How did you test it ?

Well, let's wait for Create 0.5.1h to be ported to Fabric, if it fixes "Unbreakable" tag being removed when placing the Jetpack (and Backtank) as a block, it would be a solution as well.

**Comment by PssbleTrngle** [comment]
I think both this and #121 is caused by something fabric specific, but I think I have figured it out, jetpacks should finally not have durability anymore in the next release
