### ISSUE TITLE
Netherite Jetpack only craftable with a Netherite Ingot

### ISSUE THREAD

**Issue by GamerHD286** [PssbleTrngle/CreateJetpack#124]
### What happened?

The Netherite Backtank is able to be crafted with a Netherite Ingot and a Netherite Chestplate. The Jetpack can only be crafted with a Netherite Ingot and not with a Netherite Chestplate. This bug exists on Forge and Fabric.

![2024-09-03_19 23 53](https://github.com/user-attachments/assets/fac80193-5ad8-4afb-b3bb-9aadf4101edf)
![2024-09-03_19 23 42](https://github.com/user-attachments/assets/0faf1a33-23c6-4d25-875b-35e6a216baf4)

### Loader

forge

### Mod Version

Forge 4.2.1 and Fabric 4.2.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Did not know that was a thing with the backtank, but will be included in the next version

**Comment by GamerHD286** [comment]
Thanks for fixing the bug! But just one another question, will this bug also be fixed on Fabric soon?

**Comment by PssbleTrngle** [comment]
I will probably fix it as soon as create 0.5.1.h is ported to fabric & include it in the release for that
