### ISSUE TITLE
JETPACK CRASH

### ISSUE THREAD

**Issue by Hooligan00** [PssbleTrngle/CreateJetpack#126]
### What happened?

when you pick up jetpack from ground it says something about enchantment tag. the problem is the new create update got rid of some code making this crash.

### Loader

forge

### Mod Version

1.5.3

### Minecraft Version

1.20

**Comment by theLittleStone** [comment]
Hi, see the issue https://github.com/PssbleTrngle/CreateJetpack/issues/125#issuecomment-2336555928, I have solved the problem.

**Comment by PssbleTrngle** [comment]
yes, this is a duplicate of #125
