### ISSUE TITLE
Picking up jetpacks with a wrench removes enchantments

### ISSUE THREAD

**Issue by kreffox** [PssbleTrngle/CreateJetpack#128]
### What happened?

Placing a jetpack down to charge and then picking it up with a wrench will cause all enchantments to be lost.
Picking up the jetpack normally, i.e. right-clicking and equipping it, works fine.

This was not the case one version ago.

I tested this on a minimal singleplayer instance, so all you need to reproduce it is the Create Jetpack mod + relations.

### Loader

forge

### Mod Version

4.3.0

### Minecraft Version

1.20

### Relevant log output

```Shell
none
```

**Comment by PssbleTrngle** [comment]
you will need to update create, you are probably not on the lastest version (0.5.1.h)

**Comment by kreffox** [comment]
I should have specified that: I was using the latest version for my minimal instance test: create-1.20.1-0.5.1.h.jar

Exact filenames:
create-1.20.1-0.5.1.h.jar
create_jetpack-forge-4.3.0.jar
kotlinforforge-4.11.0-all.jar

Edit: Tested on Forge 47.3.7 and 47.3.10
Have to add: this issue only happens with sneaking + right clicking the jetpack to pick it up, not with a normal right click to equip it.

**Comment by PssbleTrngle** [comment]
Seems to also happen when simply breaking it with a pickaxe, I have to updated the loot table. Will be fixed in the next release
