### ISSUE TITLE
Jetpack Controls have a bugged headline

### ISSUE THREAD

**Issue by GamerHD286** [PssbleTrngle/CreateJetpack#129]
### What happened?

Just a minor bug / suggestion for an improvement, when you are in the controls the Jetpack section is named kategories.movement.jetpack and I thought I would tell here even if this is a minor fix, it maybe is something which can be fixed in the next update or so.

The "bug" is on Fabric and Forge
![bLgSo4bWNf](https://github.com/user-attachments/assets/67fef5f5-f8bd-43ed-8a3a-ddb99eb5460a)

### Loader

forge

### Mod Version

4.3.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Seems like its missing for the `en_us` language, will add it there too
