### ISSUE TITLE
FIXED (i think)?? Newest mod version for mc 1.21.1 doesn't let players connect to server

### ISSUE THREAD

**Issue by ThePastaGuy** [PssbleTrngle/CreateJetpack#137]
### What happened?

Whenever anyone tries to join my server with the new version installed on both client and server, the error reads that the create mod version isn't the same and displays the mod version, which is the same and is the most recent. the previous version works just fine though. Great mod, love the way u can use it with the elytra, wish it was a bit smoother with do a barrel roll, but it's still nice that it works perfectly fine.

### Loader

forge

### Mod Version

4.3.2

### Minecraft Version

1.20

### Relevant log output

```Shell
"Failed to synchronize registry data from server, closing connection" 

me paraphrasing: 'the mods that dont match:'
"mod name: Create - server has: 0.5.1.h - you have: 0.5.1.h"
```

**Comment by PssbleTrngle** [comment]
Can you upload the entire log, at best from both client and server?

**Comment by ThePastaGuy** [comment]
I'm trying to reproduce it, but it seems to work just fine now. My friend was getting this issue on my server and neither of us have the logs anymore.
