### ISSUE TITLE
Durability Change

### ISSUE THREAD

**Issue by Xanth27** [PssbleTrngle/CreateJetpack#139]
### Describe the feature you have in mind.

So to keep the mod in line with the create mod, the jetpacks shouldn't have durability, similar to how the backtanks are with the create mod. Because as the mod stands currently, the jetpacks have durability, but without F3+H, you can't see it. I propose that either, the jetpack supports the Mending enchantment, or that the mod takes the same approach that base Create does, and simply do away with the durability. 

I took the liberty to test if the mending enchantment would work as intended in my singleplayer world by adding the enchantment via command: /give @p create_jetpack:jetpack{Enchantments:[{id:"mending",lvl:1}]}

I'm currently using the 1.20.1 Fabric version of the mod on a large modded server.

### Does this solve a particular problem?

Yes, it stops the jetpack from breaking when the player isn't expecting it.

**Comment by PssbleTrngle** [comment]
This definitely is a bug, they are not intended to have durability

**Comment by PssbleTrngle** [comment]
Ok looks like this is a fabric-only problem, will release a hotfix soon where durability is removed for jetpacks

**Comment by Xanth27** [comment]
Perfect thanks
