### ISSUE TITLE
[Suggestion] Added timer similar to the Diving helmet

### ISSUE THREAD

**Issue by DaLumma** [PssbleTrngle/CreateJetpack#2]
### Describe the feature you have in mind.

It would be nice if I could see how long I can continue to use it by adding a timer to the upper left corner in a simmilar way the diving helmet does it.

**Comment by PssbleTrngle** [comment]
Great suggestion

**Comment by PssbleTrngle** [comment]
Added an air indicator in form of a little air tank in the top left
