### ISSUE TITLE
Server config relies on client config

### ISSUE THREAD

**Issue by HeyNoose** [PssbleTrngle/CreateJetpack#21]
### What happened?

Changing `hover_descend` only on server side did nothing for descend speed and caused some desync issues. Possibly applies to all values.
So in order to change the configs both the server and all players client side have to configure it.

### Mod Version

1.2.1

### Minecraft Version

1.18

### Forge Version

40.1.68

**Comment by PssbleTrngle** [comment]
Config is now being synced to the client
