### ISSUE TITLE
Update for 1.19

### ISSUE THREAD

**Issue by Endrez42** [PssbleTrngle/CreateJetpack#26]
### Describe the feature you have in mind.

Please update this to Create 0.5e as soon as you are able to. This is about the only good jetpack mod in recent times that isn't just creative flight.

Yes, I'm aware it released today. Just putting this here in case it happens sometime soon and I can be notified.

Thanks.

**Comment by PssbleTrngle** [comment]
Damn you're quick 😅. I'm still on vacation, but I'll get on it as soon as I am back, don't worry.

**Comment by PssbleTrngle** [comment]
Update is out, hopefully everything works because I'm gone for another week
