### ISSUE TITLE
crashes on server 1.19.2

### ISSUE THREAD

**Issue by papillo12** [PssbleTrngle/CreateJetpack#27]
### What happened?

I installed the latest version for 1.19.2 and in the client it worked but when testing on the server it crashed.

[debug (5).log](https://github.com/PssbleTrngle/CreateJetpack/files/9690722/debug.5

[latest (15).log](https://github.com/PssbleTrngle/CreateJetpack/files/9690723/latest.15.log)
.log)

[crash-2022-10-01_16.08.04-fml.txt](https://github.com/PssbleTrngle/CreateJetpack/files/9690724/crash-2022-10-01_16.08.04-fml.txt)

### Mod Version

2.0.0

### Forge Version

1.19.2  43.1.32

**Comment by PssbleTrngle** [comment]
Should be fixed in version 2.0.1
