### ISSUE TITLE
Enchantment Config option

### ISSUE THREAD

**Issue by xbxbxb123** [PssbleTrngle/CreateJetpack#28]
### Describe the feature you have in mind.

I would really like if there was a config option for wether enchantments, besides capacity, are allowed on the jetpack. Also it would be appreciated if this was added to the 1.18.2 version of the mod and not just the newer 1.19 version.

### Does this solve a particular problem?

Yes, it balances the jetpack to not be too powerful as a replacement for armor.

**Comment by PssbleTrngle** [comment]
Currently the enchantments are in parity to what the copper backtank is able to use.
I would be a bit weird to disable enchantments for the jetpack that are useable on the backtank, but I also see that I would good for balancing things

**Comment by PssbleTrngle** [comment]
Added a config option for blacklisting enchantments in `1.4.0` / `2.1.0`
