### ISSUE TITLE
Jetpack Hover Mode Triggers In Seats

### ISSUE THREAD

**Issue by ChloeDawn** [PssbleTrngle/CreateJetpack#33]
### What happened?

The jetpack triggers and consumes pressurized air if it is in hover mode when sitting in a Create seat.
This also occurs for other rideable entities such as pigs, horses, or other mods' seats.

### Mod Version

1.4.0

### Minecraft Version

1.18

### Forge Version

40.1.80

**Comment by PssbleTrngle** [comment]
Thanks, that's a case I did not think about, will fix this
