### ISSUE TITLE
Custom Recipe?

### ISSUE THREAD

**Issue by MacChuck** [PssbleTrngle/CreateJetpack#39]
### Describe the feature you have in mind.

Is there a way to customize the recipe with a datapack? (Remove the elytra, or change other material requirements).

I have this in a custom pack but not anything like KubeJS or craft tweaker.

**Comment by PssbleTrngle** [comment]
Of course, the recipe can be modified using a datapack, just like any other recipe

**Comment by MacChuck** [comment]
Looks like it would be `data/create_jetpack/recipes/jetpack.json` ?

If so, I've done other datapacks before, so I can tackle it from there, and thanks!

**Comment by PssbleTrngle** [comment]
Yes, exactly 👍
