### ISSUE TITLE
combining with armor

### ISSUE THREAD

**Issue by ZEROX7** [PssbleTrngle/CreateJetpack#4]
### Describe the feature you have in mind.

would it be possible to make it upgradable to improve the armor ratin? would love to see it for the helmet aswell

**Comment by PssbleTrngle** [comment]
Not really thinking of that right now, I'm not the biggest fan of being able to upgrade everything, it feels a bit more balanced this way

**Comment by PssbleTrngle** [comment]
You can still enchant it with protection, just like the backtank
