### ISSUE TITLE
a Fabric port, please?

### ISSUE THREAD

**Issue by Zaroz** [PssbleTrngle/CreateJetpack#44]
### Describe the feature you have in mind.

Hello, can you please port this mod to fabric for v1.18 or 1.19? I really want to add it to the modpack that I am making, but it's a fabric modpack due to certain mod limitations/restrictions.

### Does this solve a particular problem?

It allows users of both modloaders to utilize this mod.

**Comment by LeFogel** [comment]
yes please

**Comment by PssbleTrngle** [comment]
I am thinking about this, but I have not decided yet

**Comment by PssbleTrngle** [comment]
Will happen once create fabric ports the new 0.5.1 version

**Comment by PssbleTrngle** [comment]
First fabric version is out, hopefully everything works as intended
