### ISSUE TITLE
Allow GUI to be Moved

### ISSUE THREAD

**Issue by Darkosto** [PssbleTrngle/CreateJetpack#45]
### Describe the feature you have in mind.

Hello!

Can you please allow the GUI for the jetpack to be moved? Currently, it sits on top of a number of other mod GUI elements. Having the ability to move your GUI would allow a lot more pack makers to set it in a much more convenient place.

Thank you!
Darkosto

Forge: 40.2.0
MC: 1.18.2
Create Jetpack: 1.9.6

### Does this solve a particular problem?

Yes, many mods also have GUIs that overlap with this mod:

![image](https://user-images.githubusercontent.com/10309699/212163159-1e1bda8b-7f6b-4180-a045-947a2ea7566c.png)

**Comment by PssbleTrngle** [comment]
You are totally right, I'll add some config values allowing different positioning
