### ISSUE TITLE
Allowed in Modpacks?

### ISSUE THREAD

**Issue by Iffy-cat** [PssbleTrngle/CreateJetpack#5]
### Describe the feature you have in mind.

Sorry I'm new here, dont know how to change the lable to question...
So I am creating a small Modpack for a small streamer and really liked your mod! So I wanted to ask if I am allowed to use it in my Modpack.

**Comment by PssbleTrngle** [comment]
Sure, as long as you link back to the mod in some sort of way if you publish it, but that's built-in to pages like curseforge
