### ISSUE TITLE
Config to turn elytra boost on/off

### ISSUE THREAD

**Issue by TwoHeadedGiant** [PssbleTrngle/CreateJetpack#50]
### Describe the feature you have in mind.

Add a setting in the config file to turn the jetpack's ability to boost elytra on and off

### Does this solve a particular problem?

Yes, it balances elytra in packs where there are mods such as aileron which disable elytra's ability to use rockets https://www.curseforge.com/minecraft/mc-mods/aileron

**Comment by PssbleTrngle** [comment]
I have added an option to the server config in the lastest version
