### ISSUE TITLE
Add cooldown after toggling active and/or hover to prevent double-pressing the button

### ISSUE THREAD

**Issue by wqferr** [PssbleTrngle/CreateJetpack#52]
### Describe the feature you have in mind.

Currently, me and my friend are both having some issues regarding double-presses (1 keypress counting as 2) and effectively being unable to switch on or off our jetpacks multiple times in a row. This could be solved with a simple cooldown after toggling either setting.

### Does this solve a particular problem?

Yes, the inconsistency of activating/deactivating the jetpack even when pressing the key very quickly.

**Comment by PINPAL** [comment]
+1 to this. Had to switch to using IronJetpacks due to this issue resulting in toggling the jetpack being extremely inconsistent.

**Comment by PssbleTrngle** [comment]
I've added a cooldown in the new version, let me know if the timing I selected works
