### ISSUE TITLE
jetpack can't put into back slot

### ISSUE THREAD

**Issue by hyl5942850** [PssbleTrngle/CreateJetpack#54]
### What happened?

jetpack can't be equiped in the back slot in curios,but in 1.18.2 or 1.19front version, it can

### Mod Version

1.19.2 2.1.3

### Minecraft Version

None

### Forge Version

43.2.6

**Comment by PssbleTrngle** [comment]
you would have to allow jetpacks to be put into curios' backslot like explained at the bottom of the readme file
