### ISSUE TITLE
Netherite Jetpack

### ISSUE THREAD

**Issue by Haloskitty** [PssbleTrngle/CreateJetpack#61]
### Describe the feature you have in mind.

In line with the new Create .5.1 update, add a jetpack upgrade that, similar to the new netherite backtank, creates the full netherite diving set to be immune to lava, and has the pressure aspect of the previous jetpack, as well as being able to fly.

### Does this solve a particular problem?

Having to choose between having the full netherite fire invincibility and being able to fly. Maybe it could have less armor than the regular netherite backtank or a speed debuff to compensate

**Comment by supertroopa** [comment]
I would really love this addition for my modpack so we don't need an extra curios back slot on top of the one used for backpacks to make things work properly. It's very inconvenient and the jetpack also doesn't render on the player if placed in the curios slots. Please add this, and allow us to transfer our enchantments over from our netherite backtanks and chestplates as well, please. (Also, if you're going to nerf its defense for balancing, please add something in the config to revert or modify the stats. However a jetpack speed debuff sounds reasonable.)

**Comment by PssbleTrngle** [comment]
Sorry for the very long wait, a netherite version of the jetpack has finally been added in the newest versions
