### ISSUE TITLE
[1.18.2] Jetpack is not longer usable on Curious slot

### ISSUE THREAD

**Issue by SrRapero720** [PssbleTrngle/CreateJetpack#64]
### What happened?

Tittle say all
![2023-06-07_21h49_46](https://github.com/PssbleTrngle/CreateJetpack/assets/29090346/5dc19f01-8df4-4c20-97c9-03d0ca5b1835)

### Mod Version

 create_jetpack-1.5.0.jar

### Minecraft Version

1.18

### Forge Version

40.2.9

**Comment by PssbleTrngle** [comment]
It has never been out-of-the-box, you have to configure it using a datapack like described [here](https://github.com/PssbleTrngle/CreateJetpack/blob/1.19.x/README.md)
