### ISSUE TITLE
trinkets compat

### ISSUE THREAD

**Issue by DadoIrie** [PssbleTrngle/CreateJetpack#68]
### Describe the feature you have in mind.

I've managed to add the jetpack in the back slot, but doesn't wanna work if not on the chest slot
then I've noticed that only curios compat is present, but no trinkets trinkets compat (https://github.com/PssbleTrngle/CreateJetpack/blob/1.19.x/src/main/kotlin/com/possible_triangle/create_jetpack/compat/CuriosCompat.kt)

since jetpack is available also on fabric and fabric's curios is trinket could a trinket compat be made?

**Comment by PssbleTrngle** [comment]
Definitly possible, I will look into this

**Comment by PssbleTrngle** [comment]
Jetpacks in trinket slots should now be detected in the newest version
