### ISSUE TITLE
Precise create version on release

### ISSUE THREAD

**Issue by corentin-godefroy** [PssbleTrngle/CreateJetpack#69]
### Describe the feature you have in mind.

Can you precise the compatible version of create with your mod on the name please ? Because we don't actualy know for wich one your mod is compatible 0.5.0 or 0.5.1 ?

### Does this solve a particular problem?

This solve possible confused situation and clarify wich version use with mod and implify life of modpacks creators.

**Comment by PssbleTrngle** [comment]
For 1.18, everything starting with 1.5.0 will only support create 0.5.1.
For 1.19, everything starting with 3.1.0.

**Comment by corentin-godefroy** [comment]
I'm not asking only for me, but everyone who look on curseforge.
Thank's you for you rapid answer !
