### ISSUE TITLE
crash new version

### ISSUE THREAD

**Issue by GitJhopa** [PssbleTrngle/CreateJetpack#70]
### What happened?

https://modrinth.com/mod/create/version/1.19.2-0.5.1.c new version Create + your mod jetpack = crash

### Loader

forge

### Mod Version

latest

### Minecraft Version

1.19

**Comment by GitJhopa** [comment]
[crash-2023-07-05_12.01.50-fml.txt](https://github.com/PssbleTrngle/CreateJetpack/files/11956016/crash-2023-07-05_12.01.50-fml.txt)

**Comment by PssbleTrngle** [comment]
Oh nice, actually very cool changes which makes the last mixin of this mod unneccessary

**Comment by GitJhopa** [comment]
> Oh nice, actually very cool changes which makes the last mixin of this mod unneccessary

fix start up crash?

**Comment by GitJhopa** [comment]
there came out important fixes for me, crash

**Comment by PssbleTrngle** [comment]
yeah no it totally makes sense that it crashes, since some internal create code has changed. I'm already working on updating the mod. I just noticed that the actual things that were changed are pretty nice
