### ISSUE TITLE
[1.18.2] crash updating to create 0.5.1c

### ISSUE THREAD

**Issue by SrRapero720** [PssbleTrngle/CreateJetpack#72]
### What happened?

	Caused by 2: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [create_jetpack.mixins.json:BackTankUtilMixin] from phase [DEFAULT] in config [create_jetpack.mixins.json] FAILED during APPLY

Crash report complete:
[crash-2023-07-07_20.24.27-fml.txt](https://github.com/PssbleTrngle/CreateJetpack/files/11985818/crash-2023-07-07_20.24.27-fml.txt)

Crash comes from this mixin:
https://github.com/PssbleTrngle/CreateJetpack/blob/644a122c761d14a28d8853a1e44ab4f91c0aeb10/src/main/java/com/possible_triangle/create_jetpack/mixins/BackTankUtilMixin.java#L17

### Loader

forge

### Mod Version

 create_jetpack-1.5.0.jar

### Minecraft Version

1.18

**Comment by PssbleTrngle** [comment]
There is already an update out for create 0.5.1.c support 😁

**Comment by PssbleTrngle** [comment]
Oh I'm sorry I completely forgot to read the Minecraft version number, the 1.18 hotfix has not been released yet, you can expect it in hopefully 1-2 days

**Comment by PssbleTrngle** [comment]
Should be fixed in 1.5.1
