### ISSUE TITLE
Trinkets Slot Addition

### ISSUE THREAD

**Issue by Noth-Shian** [PssbleTrngle/CreateJetpack#73]
### Describe the feature you have in mind.

Ok, I've managed to create a extra back slot with Trinkets to put the jetpack there so that way i don't have to take off the chestplate
But i actually have the same issue as [#68](https://github.com/PssbleTrngle/CreateJetpack/issues/68)
Plus i cant upload custom mods to my Aternos server so it would be nice if you can add this into the mod 

[!# Create-Jetpack-Slot.jar.zip](https://github.com/PssbleTrngle/CreateJetpack/files/11991348/Create-Jetpack-Slot.jar.zip) (Its a mod, so remove the ".zip")

![image](https://github.com/PssbleTrngle/CreateJetpack/assets/58456664/ae3c4621-b02e-4991-8834-b20057119292)

### Does this solve a particular problem?

Possibility to put on a Jetpack without taking off a chestplate

**Comment by PssbleTrngle** [comment]
I think we might need to wait out until create fabric ports the newest changes made in create 0.5.1.c, which should include native support for detecting items in trinket slots. And what do you mean by you can't upload "custom mods" to aternos, you should only need a datapack to enable the trinket support (after 0.5.1.c has been released)

**Comment by PssbleTrngle** [comment]
Should now be working in the latest version (3.3.1)
