### ISSUE TITLE
If I break the jetpack it doesn't drop out.

### ISSUE THREAD

**Issue by GitJhopa** [PssbleTrngle/CreateJetpack#75]
### What happened?

If I break the jetpack it doesn't drop out.

### Loader

forge

### Mod Version

create_jetpack-forge-3.2.0.jar

### Minecraft Version

1.19

**Comment by GitJhopa** [comment]
And also it breaks for a long time even with a pickaxe.

**Comment by PssbleTrngle** [comment]
Oh it could actually be that I forgot to add it to the `mineable/pickaxe` tag, since you can simply pick it up using a wrench or by just right clicking it

**Comment by PssbleTrngle** [comment]
Fixed in the latest release
