### ISSUE TITLE
jetpack can't put in curios back slot

### ISSUE THREAD

**Issue by willis1030** [PssbleTrngle/CreateJetpack#77]
### What happened?

jetpack can't put in curios back slot. even allowed_slots = ["back"] in setting of create_jetpack-common.toml (server side).
1.20.1

### Loader

forge

### Mod Version

create_jetpack-forge-4.0.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Hey, you still have to enable the jetpack in the slot using a datapack, you can read about it in the last section of the README.
I'm actually thinking if that config option is misleading and I should probably remove it completely

**Comment by PssbleTrngle** [comment]
I think I will also create an example datapack for this usecase

**Comment by PssbleTrngle** [comment]
datapack has been created, you can download it [here](https://github.com/PssbleTrngle/CreateJetpack/raw/1.19.x/curios_support_datapack.zip)

**Comment by NolanHewitt** [comment]
how would I do this for trinkets instead of curios?

**Comment by PssbleTrngle** [comment]
That's described in the README file of the [fabric repository](https://github.com/PssbleTrngle/CreateJetpack-Fabric)

**Comment by NolanHewitt** [comment]
Thank you. Turns out an even easier way to make it work is by editing the elytra slot fabric mod for people who don't want to make a datapack, adding two lines of text in one of the files makes it work.

**Comment by PssbleTrngle** [comment]
I mean the elytra slot fabric mod is also almost just a datapack

**Comment by willis1030** [comment]
Yes, it solved. and I have learned how to solve it now! thanks for all these reply.
