### ISSUE TITLE
Jetpack loses tier when placed down

### ISSUE THREAD

**Issue by teaperr** [PssbleTrngle/CreateJetpack#80]
### What happened?

With the TieredZ mod ( https://modrinth.com/mod/tieredz ) whenever the jetpack is placed as a block it will lose its tier when picked up again.

### Loader

fabric

### Mod Version

1.2.7

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
Does this also happen with the backtank block, because I'm pretty sure I use the same logic?

**Comment by teaperr** [comment]
You're right, sorry about that. I'll put this on create's git page instead and hopefully they can sort it out

**Comment by xllifi** [comment]
> Does this also happen with the backtank block, because I'm pretty sure I use the same logic?

https://github.com/Globox1997/tiered/issues/70

**Comment by PssbleTrngle** [comment]
I'll close this since I feel like this should be rather handled by tiered itself
