### ISSUE TITLE
[Fabric] Jetpack seems to have no effect on swimming/elytra

### ISSUE THREAD

**Issue by DCobley** [PssbleTrngle/CreateJetpack#82]
### What happened?

With the Fabric version of the mod, the Jetpack seems to have no effect on swimming, and very little effect on the Elytra.

### Loader

fabric

### Mod Version

4.0.0

### Minecraft Version

1.20.1

**Comment by NolanHewitt** [comment]
I'm noticing this as well. Swimming speed isnt changed.

**Comment by GamerTable** [comment]
Same

**Comment by PssbleTrngle** [comment]
Yes, the swim speed was not implemented yet, seems like a overlooked that. It's working now in the newest release
