### ISSUE TITLE
Save jetpack hover status on world reload

### ISSUE THREAD

**Issue by InqGilgamesh** [PssbleTrngle/CreateJetpack#83]
### Describe the feature you have in mind.

Currently, if hover mode is enabled and the player exists and reloads the world, hover mode is reset and disabled.  It would be appreciated if hover mode was saved on player exit and was synced on player entry.

**Comment by PssbleTrngle** [comment]
Toggle keys should now be saved between world save/loads.
They are still not persisted when closing/reopening the game tho
