### ISSUE TITLE
Configurable Elytra boost?

### ISSUE THREAD

**Issue by thrilliams** [PssbleTrngle/CreateJetpack#87]
### Describe the feature you have in mind.

I've been playing around with this mod for a little while and I've noticed that, for me, the boost given to Elytra flight is so small as to be almost imperceptible. I think it would be useful and much appreciated by at least me if you could add some options to change the speed given in Elytra flight somewhere in the config file. Thanks!

### Does this solve a particular problem?

Right now, the Elytra boost is not even a sidegrade to firework rockets. Fireworks are both significantly faster and far more convenient. If the boost was brought up some, it would make the two options for powered flight more comparable.

**Comment by PssbleTrngle** [comment]
The newest version has turned the elytra boost config option from a simple toggle into a decimal value which is used as factor.
This means 1.0 would chance nothing. 
The default value has also been increased from 1.0  to 1.25.
To get the same boost as a firework rocket, you would have to use 1.5
