### ISSUE TITLE
Elytra Boost don't work

### ISSUE THREAD

**Issue by mikaba-eu** [PssbleTrngle/CreateJetpack#89]
### What happened?

I don't get the elytra boot working. I did read that you mean by "UP" the spacebar or "jump" button. But that does nothing.

### Loader

fabric

### Mod Version

3.3.1

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
I'll take making it configurable into consideration. This issue will be closed since #87 is also asking for this
