### ISSUE TITLE
Nice whoosh noise!

### ISSUE THREAD

**Issue by forthwist** [PssbleTrngle/CreateJetpack#9]
### Describe the feature you have in mind.

Ok, maybe it has one and this is a bug and if not I'm sure this is already planned...
But the feedback of activation/flight and hover noises would make the experience just fantastic.

Sorry to bombard with bugs and requests--it's born from excitement, this is an awesome little mod and fits so perfectly in our server pack!

### Does this solve a particular problem?

Positive feedback for activation/differentiates hover from slowfall potion.

**Comment by PssbleTrngle** [comment]
Definitely something I'll look into, sound feedback polishes every feature so much.

And thanks for the nice message, you made my day ❤️
