### ISSUE TITLE
Trinkets support broken

### ISSUE THREAD

**Issue by skippyall** [PssbleTrngle/CreateJetpack#93]
### What happened?

Since Create Jetpacks 4.1.0, Jetpacks don't work in the back slot of Trinkets anymore. You can still put them into the slot when enabled with a datapack, but you can't fly.

### Loader

fabric

### Mod Version

4.1.0

### Minecraft Version

1.20

**Comment by JoshT90** [comment]
Currently experiencing similar issue. Followed steps on Trinkets and Create Jetpack Fabric repository, unable to get data folders or datapack to allow for jetpacks to be placed in back slot

**Comment by SageofTurtles** [comment]
I'm experiencing this issue as well.  Can place the jetpack in the Trinkets "back" slot, but the icons that show when wearing the jetpack do not display, and I am unable to use the jetpack at all if it's not in the vanilla chest slot, both with and without elytra equipped.

**Comment by PssbleTrngle** [comment]
Fixed in the new release
