### ISSUE TITLE
Jetpack can't be used while Elytra are activated

### ISSUE THREAD

**Issue by SageofTurtles** [PssbleTrngle/CreateJetpack#94]
### What happened?

When equipping both the Jetpack and the Elytra (which I tried by creating the Trinkets-compatible datapack as shown on the Github page, and also using the recommended Elytra Slot mod instead of the datapack), I am unable to use the jetpack while my elytra are active.  I can use the jetpack while wearing the elytra before they have been activated, but once I press space a second time to enter glide mode, the jetpack no longer has any effect when pressing space again until I've landed.  (Was expecting a rocket-like boost from this action, as described in the Readme and on Modrinth.)

Using the latest Fabric version of the mod & Minecraft 1.20.1, along with Create Fabric 0.5.1-d.  Also using Trinkets 3.7.1 and have tried both with and without Elytra Slot 6.3.0.

### Loader

fabric

### Mod Version

4.1.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Pretty sure this is either related to a too low boost from the elytra #87 or the broken trinket support #93, hopefully both will be fixed soon
