### ISSUE TITLE
I need jetpack in forge 4.3.0

### ISSUE THREAD

**Issue by dakibo** [PssbleTrngle/CreateJetpack#97]
### Describe the feature you have in mind.

im playing forge 1.20.1. im want play jetpack mod in minecraft. buk minecraft say "need 4.30!" please make forge 4.3.0

**Comment by PssbleTrngle** [comment]
Can you attach a screenshot of the error screen you are getting?

**Comment by dakibo** [comment]
![2024-01-24](https://github.com/PssbleTrngle/CreateJetpack/assets/157568501/4ab7c5a7-0539-4cab-82dd-9c4edeeb1baf)
here

**Comment by PssbleTrngle** [comment]
you're missing [Kotlin For Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
