### ISSUE TITLE
No recipe in REI or on mod's page

### ISSUE THREAD

**Issue by SunsetJesus4653** [PssbleTrngle/CreateJetpack#99]
### What happened?

REI will not show me how to craft the jetpacks, and the recipe is not shown anywhere on the CurseForge page. I can't use this mod because I have no idea how to craft the jetpacks. I couldn't find it anywhere on google, either.

### Loader

fabric

### Mod Version

Fabric 4.1.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Is there support for mechanical crafting recipes (or any create recipe types in general) in REI?

**Comment by SunsetJesus4653** [comment]
> Is there support for mechanical crafting recipes (or any create recipe types in general) in REI?

Yes in my experience so far, there have only been two or three Create recipes that didn't show up in REI. Also, the jetpack recipe now shows up as well. Nothing was changed to cause this.

**Comment by SunsetJesus4653** [comment]
Yes in my experience so far, there have only been two or three Create recipes that didn't show up in REI. Also, the jetpack recipe now shows up as well. Nothing was changed to cause this.
